### ISSUE TITLE
Issues AttributeError: 'Parameter' object has no attribute 'new'

### ISSUE THREAD

**Issue by 666zcli** [yl-1993/ConvDeltaOrthogonal-Init#1]
Hello, when I want to duplicate your result and run the code. The results shows that AttributeError: 'Parameter' object has no attribute 'new'. Could you give me some advice? Thanks

**Comment by yl-1993** [comment]
@666zcli I think the error raised by [this line](https://github.com/yl-1993/ConvDeltaOrthogonal-Init/blob/701d8830af91a23bb6b121acc41a4c4c0c659e58/_ext/nn/init.py#L32). Basically there are two choices.
1. Upgrade your PyTorch to 0.4.0 or above and check the following snippet works fine.
```
from torch.nn.parameter import Parameter
a = Parameter(torch.FloatTensor(3, 4))
a.new(3, 4).normal_(0, 1)
```
2. Replace the line with similar function to create and init the tensor under your PyTorch version.
